---
title: "Dashboard about Abalones"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# The flexdashboard package should be installed
library(flexdashboard)

# load other packages needed for code chunks
library(readr)
library(tibble)
library(dplyr)
library(ggplot2)

# import abalone.csv dataset
# use read_csv()
# function from readr to import data
abalone <- read_csv("abalone.csv")
```

Column {data-width=450}
-----------------------------------------------------------------------

### Glimpse of Abalone Data

Use the `glimpse()` function from the `tibble` package to take a peak at the **abalone** dataset. 

```{r dataglimpse}
# get a glimpse of the data
# use glimpse() function from tibble package
glimpse(abalone)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Plot of Abalone Rings by Shell Weight

```{r plot}
# make plot of number of rings by shellWeight
ggplot(abalone, aes(shellWeight, rings, color=sex)) +
  geom_point() +
  geom_smooth()
```

### Regression of Abalone Rings by Shell Weight

We can save regression model results, then put the model coefficients from the `summary()` function into a nice table using the `kable()` function from the `knitr` package.

```{r regmodel}
model1 <- lm(rings ~ shellWeight, data=abalone)
sum_model1 <- summary(model1)
knitr::kable(sum_model1$coefficients)
```

